# Site settings
username: sarma_ba
facebook_page_name: SarajevoRubyMeetups
title: Sarajevo Ruby Meetup
email: damirz@gmail.com
description: "Sarajevo Ruby users meet up every third Thursday of a month at 18:00."
baseurl: ""
url: "http://sarma.ba"
twitter: "https://twitter.com/sarma_ba"
github: "https://github.com/sarma-ba"
agenda: "http://t.co/9Fq8FfL62A"
ga_ua: "UA-467461-12"

# Build settings
markdown: kramdown
permalink: pretty
